src/dnscachedresolver.cpp

Improves the behaviour of #224. Tested by setting my Bono node's upstream_hostname to news.bbc.co.uk and checking the logs:
```
30-12-2014 11:46:40.513 UTC Debug dnscachedresolver.cpp:154: Wait for query responses
30-12-2014 11:46:40.513 UTC Debug dnscachedresolver.cpp:384: Received DNS response for news.bbc.co.uk type A
30-12-2014 11:46:40.514 UTC Debug dnsparser.cpp:90: Parsing DNS message
000000: c7ff8180 00010003 00000000 046e6577 73036262 6302636f 02756b00 00010001    .... .... .... .new s.bb c.co .uk. ....
000020: c00c0005 00010000 02db0014 076e6577 73777777 03626263 036e6574 02756b00    .... .... .... .new swww .bbc .net .uk.
000040: c02c0001 00010000 00830004 d43af43b c02c0001 00010000 00830004 d43af43a    .,.. .... .... .:.; .,.. .... .... .:.:
30-12-2014 11:46:40.514 UTC Debug …
```

[Reviewer: Ellie] Discard DNS responses other than A/AAAA/SRV/NAPTR with a warning

---

include/memcachedstore.h
include/memcachedstoreview.h
src/memcachedstore.cpp
src/memcachedstoreview.cpp

Previously, servers and new_servers had to share a prefix, because MemcachedStoreView returned indexes into an array of memcached connections (so if your servers[0] didn't match new_servers[0], read attempts would go to a different memcached and fail).
This change makes MemcachedStoreView return the address of the relevant memcached server directly, rather than an index, allowing for new_servers to have any (or no) overlap with servers. This mostly just makes use of information it already has - it's not a very big change.
This substantially mitigates https://github.com/Metaswitch/sprout/issues/852 - it doesn't do hinted-handoff-style rebalancing but it is now possible to do a "create new VMs" upgrade with no risk of an outage by adding new memcacheds to the end and then removing the old …

Remove the need for a relationship between servers and new_servers in MemcachedStoreView

---

src/httpconnection.cpp

Leaving as a pull request until I next do a cpp-common merge.

[No review required] Fix unused variable warning

---

include/dnscachedresolver.h
src/dnscachedresolver.cpp

We discussed earlier how the existing code probably doesn't behave how it's meant to (because records expire on schedule, so by the time we've realised that the DNS server hasn't responded, we've deleted the old records). This should improve that.
The basic change is that we add 5 minutes to the expiry time when working out when to free records, so there's a period where it has expired (and we'll re-query the DNS server) but is still in memory (and so we can re-use it if the server is down).
I also spotted that the existing code sets `ce->expires = 30` but I think it should be an epoch timestamp - I added a check to `add_to_expiry_list` to ensure this.
I haven't tested this yet (or even compiled it), but wanted to get it out for review to check the approach. In particular, this is meant …

[Reviewer: Andy] Preserve old DNS records if the server doesn't respond

---

include/dnscachedresolver.h
src/dnscachedresolver.cpp
test_utils/test_interposer.cpp

I'm guessing that it was just luck that the code generated by Ubuntu 12.04's tools chain (gcc 4.6.3) got away without having a copy constructor for DnsResult, since the shallow copy performed by the default copy constructor for DnsResult causes a double delete of the pointers stored in the _records vector. Regardless, the double delete causes a crash (sig 11) on loads built with Ubuntu 14.0.4's gcc tool chain. This error prevents an Ubuntu 14.04 built sprout from ever completing its initialization causing an endless crash loop.
Also, I had to add support in the test_iterposer for glibc 2.4.0.

Fixes for port to Ubuntu 14.04's tools chain (gcc 4.8.2)

---

include/dnsrrecords.h
src/dnscachedresolver.cpp
src/dnsparser.cpp

Builds on #225 to fix #224 more fully (but I think it's a bit more controversial which is why I pulled #225 out separately). With this change, if we get a DNS answer that contains a CNAME pointing at Y, and then some A/AAAA records for Y, we'll use them. For example, this will work:
```
news.bbc.co.uk          599     IN      CNAME   newswww.bbc.net.uk
newswww.bbc.net.uk      300     IN      A       212.58.246.130
newswww.bbc.net.uk      300     IN      A       212.58.246.129
```
but 
```
newswww.bbc.net.uk      300     IN      A       212.58.246.130
newswww.bbc.net.uk      300     IN      A       212.58.246.129
news.bbc.co.uk          599     IN      CNAME   newswww.bbc.net.uk
```
will result in the two A records being thrown away with a LOG_WARNING. And if we just get:
`news.bbc.co.uk …

[Reviewer: Ellie] Further CNAME work

---

src/httpconnection.cpp

Fixes #200 . I'm pretty confident that this is the fix, but I'll test by spinning up two Homestead nodes, stopping one, and ensuring that the live tests still pass.

[Reviewer: Alex] Drop special handling of CURLE_COULDNT_CONNECT

---

src/diameterstack.cpp

Fixes one of the two unhelpful logs you spotted in #107. I don't think the second log is worth fixing (per my analysis in #107) - do you agree that we can close #107 after this fix?
I'll test by configuring Homestead with `hss_hostname=1.2.3.4` or something equally spurious, and checking the logs.

[Reviewer: Matt] Handle the case where we erase our peer and end up with an empty list

---

include/sasevent.h

Because you can't update SAS events without a really boring cpp-common update...

[Reviewer: Andy] Update resource bundle version number

---

test_utils/mock_sas.cpp

Tested by compiling and running the Sprout UTs - this change lets them link correctly.

[Reviewer: Alex] Enhance mock_sas.cpp to match sas-client changes

---

include/diameterstack.h

Hi Andy,
Can you review this change to the diameter stack to expose freeDiameter's fd_dictfct_Time_interpret method for creating a time_t object from a Time AVP?
Thanks,
Graeme

Reviewer AMC: Expose Time AVP values

---

src/cassandra_store.cpp
src/dnscachedresolver.cpp
src/exception_handler.cpp
src/httpconnection.cpp
src/memcachedstore.cpp

Fixes https://github.com/Metaswitch/sprout/issues/621. See my comment in there for why.
I've grepped cpp-common, sprout, chronos, ralf and homestead for pthread_key_create calls - only cpp-common and sprout had any (sprout just had one in enumservice.cpp, which I'll fix up without review once this is OKed).

[Reviewer: Alex] Fix HttpConnection segfault (and other potential ones)

---

src/zmq_lvc.cpp

Spotted some logs like:
`09-04-2015 16:54:05.748 UTC Debug zmq_lvc.cpp:285: Replaying cache for entry 0x1ded608 (length: 31341008)`
I realised that the very high length was because we were passing a pointer rather than the vector size. This fixes that.

[Reviewer: Ellie] Fix log to use correct variables

---

include/sasevent.h
src/diameterstack.cpp

This PR contains two main changes:
* Add SAS correlation to the diameter stack based on diameter session ID. 
* Split out the datestamp from the resource bundle name (to allow us to define other resource bundles in future.

[Reviewer: Ellie] sto1264 changes

---

src/load_monitor.cpp
test_utils/test_interposer.cpp

Follow-on to https://github.com/Metaswitch/cpp-common/pull/281.
Trivial changes - allowed CLOCK_MONOTONIC_COARSE to be controlled by the UT time controls, clarified some logs.
More interesting change - smoothed_latency started at 0. This meant that if your first 20 requests are all dead-on your target latency of 100ms, the smoothed latency is actually about 92ms, and your bucket rate increases. I think that's wrong, so I've defaulted it to target_latency.

[Reviewer: Alex] Fixes to the load monitor for UTability

---

src/alarmdefinition.cpp

Needed to pass clearwater-snmp-handlers UT.

[No reviewer] Trim alarm text to sub-255 characters

---

src/httpstack.cpp

Tested live with default bind address (localhost, resolving to ipv6 address), bind address set to localhost (ipv6), bind address set to localhost (ipv4), bind address set to the local ip (ipv4), bind address set to 127.0.0.1 and bind address set to ::1. Anything else worth testing?
Fixes https://github.com/Metaswitch/chronos/issues/128.

Reviewer AMC: Don't pass localhost straight through to evhtp_bind_socket

---

include/memcachedstoreview.h
include/store.h
src/memcached_config.cpp
src/memcachedstoreview.cpp

This suppresses one instance of log spam we discussed (128 lines of empty memcached view) and fixes up cluster_settings parsing so that:
```
servers=
new_servers=10.0.0.1:11211
```
is treated properly. I've tested live.

[Reviewer: Ellie] Memcached fixes

---

src/memcached_config.cpp

This supports comments in the memcached configuration files (part of the fix for https://github.com/Metaswitch/clearwater-etcd/issues/34)

[Reviewer: Alex] Support comments

---

include/cpp_common_pd_definitions.h
include/memcached_config.h
include/pdlog.h
src/memcached_config.cpp
src/memcachedstoreview.cpp

This adds ENT logs for memcached resize. I've also allowed variable interpolation in the cause/effect/action sections of PD logs, just in the message.
Example text below (though note that I moved 'There are now %d nodes in the cluster.' into the log description after testing this).

[Reviewer: Alex] ENT logs for memcached resize

---

include/sasevent.h
src/httpconnection.cpp

Hi Matt,
This change adds a NONE level to the set of SAS HTTP log levels, and implements it in httpconnection.
Along with a corresponding Chronos change, this stops Chronos from creating (and just dropping) SAS events. Tested by running stress with and without these changes - CPU usage was 50% higher without these changes.
Thanks,
Graeme

Reviewer MIRW: Add a NONE level for HTTP SAS Logging

---

include/httpstack.h
src/httpstack.cpp
src/httpstack_utils.cpp
test_utils/mockhttpstack.hpp

This stops us from including any response from the Ping Handler in our latencies
Fixes #306

[Reviewer: Matt] Don't count ping handler responses

---

include/snmp_includes.h

(This conflicts with a #define in gmock.)

[No reviewer] Undefine ACTION after including snmp headers

---

src/snmp_accumulator_table.cpp

In my new SNMP stats code, I miscalculated variance, and put the HWM and LWM in the opposite columns. This is a trivial fix to fix that.
Tests in a separate PR.

[Reviewer: Matt] Fix variance, HWM and LWM

---

src/snmp_agent.cpp

We shouldn't be calling `shutdown_agent()` ourselves (and don't in clearwater-fv-test). Tested live, fixes a crash I was seeing.

[Reviewer: Ellie] Prevent double free on SNMP shutdown

---

src/snmp_agent.cpp

Hopefully reasonably self-explanatory - netsnmp lets you provide a callback for logging, so I've done that and written a callback that logs to our normal log. (Previously, it went to syslog.)

[Reviewer: Ellie] Log net-snmp messages to the Clearwater log

---

include/snmp_internal/snmp_counts_by_node_type_table.h
include/snmp_internal/snmp_table.h
include/snmp_node_types.h
include/snmp_single_count_by_node_type_table.h
src/snmp_single_count_by_node_type_table.cpp

The big change here is the addition of an `add` method to SNMP::ManagedTable where you can provide the row directly, instead of having it constructed by new_row. This makes more sense for tables where all the rows are constructed up front.
I've also used NodeTypes a bit more widely - I'm not sure if this is sensible (I'm happy to back it out and use ints and a cast).

[Reviewer: Ellie] Attempt to shrink the per-node stats boilerplate

---

src/httpconnection.cpp

Andy,
Please can you review this (pretty self-explanatory) change to fix #335?  Note that clearwater_sas_resource_bundle.yaml already tries to decompress these using the HTTP SAS compression profile.
Thanks,
Matt

[Reviewer: Andy] Use HTTP SAS compression profile when logging HTTP requests

---

include/dnscachedresolver.h
src/dnscachedresolver.cpp

This fixes https://github.com/Metaswitch/cpp-common/issues/246, mostly by porting code from Sprout's ENUM code.
I've given the resolver three constructors - one with a single IP address as a string, one with multiple IP address as strings, and one taking IP46Addresses directly (so that the ENUM resolution code can plug into this).

[Reviewer: Andy] Allow IPv6 DNS servers

---

src/dnscachedresolver.cpp

Two fixes:
* DnsCachedResolver previously ignored 0.0.0.0 as an IP. I've restored this behaviour.
* We never delete DnsTsx objects (and didn't notice previously, because 0.0.0.0 was our IP address in UT...). They now self-destruct at the end of their useful life.
I'm going to throw together a test in clearwater-fv-test to query Google Public DNS and ensure that there are no other DnsCachedResolver leaks.
I might also fake out ares_query() so that the Sprout UTs can hit all of DnsCachedResolver.

[Reviewer: Andy] Fix memory leak failures in UT

---

include/snmp_node_types.h
include/snmp_single_count_by_node_type_table.h
src/snmp_single_count_by_node_type_table.cpp

As discussed on Friday, this lets you define what node type rows should be in a table when you create it, rather than hardcoding a list in cpp-common.

[Reviewer: Graeme] Allow the supported node types to be defined when creating a table

---

include/alarmdefinition.h

Updating the alarms comment to cover the moved cluster/config alarm IDs

[No reviewer] Update alarms comment

---

include/snmp_internal/snmp_time_period_table.h
src/snmp_continuous_accumulator_table.cpp
src/snmp_counter_table.cpp
src/snmp_event_accumulator_table.cpp
src/snmp_success_fail_count_by_request_type_table.cpp
src/snmp_success_fail_count_table.cpp

Previously the update time function could be called and it would have a (slightly) different time to when the original function was called. 
It is now required to pass a timspec value into update time, which will generally be when the function will be called, to ensure consistency

[Reviewer: Matt] - Made the update time function in time period table more consistent

---

src/snmp_continuous_accumulator_table.cpp

Resulting in the variance being 0 for a lot of the time. Also catches a divides by 0 error (that the initial conditional was meant to fix!)

[Reviewer: Matt] Conditioning on the wrong variable fix

---

src/snmp_cx_counter_table.cpp

Rob,
Please can you review this safety fix to https://github.com/Metaswitch/homestead/issues/255?  I think there's a question as to whether we should also have an "other" counter, to count any other response codes we receive - thoughts?
Matt

[Reviewer: Rob] Only increment statistics for response codes we know about

---

include/httpconnection.h
src/httpconnection.cpp

A fairly simple change to allow a certain `send_put` method to specify HTTP headers to put on the request. Tested as part of the other code reviews I have sent you.

[Reviewer: Rob] Allow PUTs to specify extra headers

---

src/cassandra_store.cpp

Graeme, can you review this change to catch an exception if the schema hasn't been set up, and put the reason in the trace, e.g.:
```
Error cassandra_store.cpp:189: Store caught InvalidRequestException: Keyspace 'homestead_cache' does not exist)
```
Fixes #382

[Reviewer: Graeme] Catch exception if there's no keysapce set up

---

include/baseresolver.h
include/diameterstack.h
include/realmmanager.h
include/sasevent.h
src/baseresolver.cpp
src/diameterstack.cpp
src/realmmanager.cpp
test_utils/mockdiameterstack.hpp

Hi Andy,
Please can you review these cpp-common changes to allow us to take into account SRV priority when routing Diameter messages?
The bulk of the work here is to refactor the existing code to make it more usable. Specifically, I've made RealmManager the sole manager of Diameter peers (removing the Diameter Stack's list of them), and I've tried to keep freeDiameter out of the RealmManager (instead using the Diameter Stack as the interface to freeDiameter), and I've made RealmManager an application of the Diameter Stack, so that the Stack doesn't know anything about RealmManager.
In addition to this, RealmManager now keeps track of the peers as a map rather than a vector, so that we can easily look up the Peer object when we get a call back. This is important because we now need to do …

Reviewer AMC: SRV priority and Diameter routing

---

include/sasevent.h
src/cassandra_store.cpp

Use TWO in reads rather than LOCAL_QUORUM/QUORUM. 
UT'd in Homestead (not yet tested as chef is playing up)

[Reviewer: Alex] Use TWO in reads

---

include/baseresolver.h
src/realmmanager.cpp

Two fixes:
- sets default values for priority and weight - these will otherwise be uninitialized for A records
- stops SRV priorities from making a score negative
I haven't risked any of the multiplication stuff - I thought about it, but got nervous about possible integer overflow issues.

[Reviewer: Graeme] Avoid issues with high SRV priority values

---

include/load_monitor.h
src/load_monitor.cpp

Fixes https://github.com/Metaswitch/cpp-common/issues/384 using the approach discussed there.
I've UTed, and I'll live test by running light stress with SIPp and checking that this doesn't cause stress to go badly wrong.

[Reviewer: Alex] Don't increase our token rate spuriously during slow periods

---

include/diameterstack.h
include/httpstack_utils.h
src/diameterstack.cpp

Andy, please can you review this change to:
* Send flush markers when a HTTP/Diameter task is completed. 
* Suppress SAS logging of diameter connection management flows.
I tested this by running the live tests and checking that they worked, and that my SAS lint reported no unflushed trails related to diameter/HTTP transactions.

[Reviewer: AMC] Send flush markers and suppress connection management logs

---

include/current_and_previous.h
include/snmp_continuous_increment_table.h
src/snmp_continuous_accumulator_table.cpp
src/snmp_continuous_increment_table.cpp
test_utils/mock_increment_table.cpp
test_utils/mock_increment_table.h

The cpp and header for the new continuous_increment_table . 
This is essentially the same as the accumulator table, but with the api altered to accept increment and decrement. as such the main statistics function now accepts a timespec set in the api functions, as well as the data values. 
Increment and decrement pass on the data, time and modification values to count_internal, which takes the current data value, modifies it correctly, and passes it all on into accumulate_internal, which still holds all of the statistics calculations.
Linked to MIB PR https://github.com/Metaswitch/clearwater-snmp-handlers/pull/94

Increment table Implementation - Reviewer EM

---

src/namespace_hop.cpp

This is to fix issue #408 
This should stop it returning a 0 on 'error', which would happen, according to http://linux.die.net/man/2/recvmsg, if the peer has performed an orderly shutdown. This fixes an error where listing a sas in shared_config, but not restarting clearwater-infrastructure to add it to the whitelist, causes sprout to become unresponsive and fall into a restart loop, caused by receiving file descriptor '0' for a socket.
I am not sure what essentially copying https://github.com/Metaswitch/sas-client/blob/clearwater/source/sas.cpp#L403 across would do, as i'm not quite sure why the differences have evolved, or what ramifications changes would make, so this PR is just to fix the bug that was causing sprout to become unresponsive and be shut down by monit.
The code still …

[Reviewer: Andy] recv_file_descriptor return -1 on error

---

src/snmp_infinite_timer_count_table.cpp

* Fix GET_NEXT to be able to backtrack correctly
* Limit tags to capital ASCII letters
* Limit tags to 16 characters
* Fix up leaving the table when you go over the end
The `find_next_oid` function is entertainingly complex but I couldn't see a nice way to eliminate the redundancies.  Tested with a live Chronos instance and `snmpwalk`.
```
$ snmpwalk -c public -v2c localhost $table.3.82.69.71 # REG
iso.2.826.0.1.1578918.999.3.82.69.71.2.1 = Gauge32: 0
iso.2.826.0.1.1578918.999.3.82.69.71.2.2 = Gauge32: 0
iso.2.826.0.1.1578918.999.3.82.69.71.2.3 = Gauge32: 0
iso.2.826.0.1.1578918.999.3.82.69.71.3.1 = Gauge32: 0
iso.2.826.0.1.1578918.999.3.82.69.71.3.2 = Gauge32: 0
iso.2.826.0.1.1578918.999.3.82.69.71.3.3 = Gauge32: 0
iso.2.826.0.1.1578918.999.3.82.69.71.4.1 = Gauge32: 0 …
```

Reviewer Rob - Fix infinite table

---

include/utils.h
src/utils.cpp

Adds a utility function for parsing http URLs into their components (server name and path).

Add Utils::parse_http_url

---

include/memcachedstore.h
src/memcachedstore.cpp

This adds a new MemcachedStore constructor, which just directs all traffic to 127.0.0.1:11211.
I've left all the rest of the code in although Sprout/Ralf/etc. no longer need much of it - this is because:
* you're going to need it for Astaire
* the more of this we rewrite, the more painful merges will be
* some of it is useful - e.g. trying twice to workaround a memcached connection reuse bug
* my use-case is genuinely a special case of the general use-case - I need to connect to one server with one vbucket and one replica

[Reviewer: Alex] Allow construction of a localhost-only memcached

---

src/namespace_hop.cpp

clang is a bit fussier about initialization, apparently

Clean compile under clang

---

src/cassandra_store.cpp

Andy, as discussed yesterday, our HA get code had a bug where we didn't trap timeout exception properly. Tested in UT and live. 
Not the prettiest of code but I didn't think it was worth the effort to tidy it up. Shout if you disagree.

[Reviewer: Andy] Catch a thrift timeout exception and retry when doing a HA get

---

include/httpstack.h
src/httpstack.cpp

All our builds have `-fno-write-strings` enabled because this function forgot to put `const` on one of it's arguments.  Disabling compiler checks makes me a sad :panda_face: so here's the fix.

Reviewer Rob - HTTPStack registers handlers by const string

---

src/memcachedstore.cpp

Hi Alex,
Please can you review this change to treat NOTFOUND as a DATA_CONTENTION when trying to do a CAS update. Currently we return an ERROR. A client should retry data contentions, which should change the flows to something like the following.
* Client attempts a CAS update which fails because the primary memcached has no record of the key (for some reason - presumably it's just crashed).
* Client receives a DATA_CONTENTION error and so does a GET.
* The primary memcached still has no record of the key, but the backup does. The value is returned, and a CAS of 0 is returned.
* The client now does an add (since the CAS has been set to 0). This succeeds on the primary and is replicated to the backup.
I'm just proposing to merge this into the 3sitegr branch.
Thanks,
Graeme

Reviewer AJH: Treat NOT FOUND as a DATA CONTENTION on a CAS

---

src/snmp_infinite_base_table.cpp

This resolves https://github.com/Metaswitch/clearwater-infrastructure/issues/259. I've chosen to just skip the infinite table if we come in before the first element:
* this is a lot safer and more maintainable than reworking netsnmp's inclusion/exclusion code
* the current behaviour isn't that unreasonable except when faced with an infinite table
* there's no valid use-case for walking the whole infinite table

[Reviewer: Andy] Skip the infinite table if we come in too early

---

include/dnscachedresolver.h
src/dnscachedresolver.cpp

Needed for clearwater-fv-test, so we can run dnsmasq on an unprivileged port then talk to it.

[Reviewer: Andy] Allow customising the UDP port for DNS

---

src/astaire_resolver.cpp

The Astaire resolver may need to resolve something of the form <host>:<port> according to the spec, and I don't think it currently does. This addresses that issue.
Graeme

Reviewer AJH: Check for port in astaire resolver

---

include/communicationmonitor.h
include/cpp_common_pd_definitions.h
src/communicationmonitor.cpp
src/httpconnection.cpp
test_utils/mockcommunicationmonitor.h

Andy, can you review this fix to add ENT logs to the communication monitor (so that the per call ENT logs can be dropped).
Fixes #317

[Reviewer: Andy] Integrate ENT logs with communication monitor

---

src/memcachedstore.cpp

Graeme, please can you review this PR to blacklist an Astaire when it fails? I've checked that all the FV tests still run successfully. I've not added a test to check the node is actually blacklisted, as this is difficult to do in the FV tests without snooping the network traffic.

[Reviewer: Graeme] Blacklist Astaires when they fail

---

include/logger.h
src/logger.cpp
test_utils/test_interposer.cpp
test_utils/test_interposer.hpp

As part of issue 383, we should attempt to reopen a log file every 5s until we succeed. This change adds that function, and also unit test infrastructure to allow us to control the results of attempting to open a file.
Tested through Sprout unit tests, and live.

[Reviewer AJH] Retry attempt to open log file after 5s.

---

src/alarm.cpp

This reverts commit 4067544d2c2c3c9207aae0624090e15a0aa53b19.
This inadvertently made the UTs retransmit alarms much faster, which exposed https://github.com/Metaswitch/clearwater-snmp-handlers/issues/127.
I think the idea of the fix is still good (check for overflow over a billion nanoseconds) but it should be implemented differently.

Revert "Fix up handling of nanoseconds"

---

include/alarm.h
src/alarm.cpp

Don't spawn threads in things created statically, instead spawn the thread lazily the first time someone calls into `AlarmManager::get_instance()` which happens (among other times) when alarms are defined.  This means you should always wait until after demonizing/forking before defining alarms but this is a pretty reasonable requirement.
Also fixed up a locking mistake (we weren't protecting access to the list of registered alarms even though we iterate over the list in another thread).
Testing done:

Reviewer Rob - Create the alarm_resend thread lazily

---

include/alarm.h
src/alarm.cpp

Don't leak the `AlarmManager`.  I'll raise an issue for the use of `start-stop-daemon --daemonize`.

Reviewer Rob - Store the AlarmManager in a unique pointer to prevent leaks

---

include/alarm.h
src/alarm.cpp
src/communicationmonitor.cpp
test_utils/mockalarm.h

The main alarm changes. 
- Removed clear_all function
- Added get_alarm_state function, and associated enum
- altered communication_monitor alarm raising
- Alarms now start with severity pointing to NULL
I will link the pull request for cpp-common-test that covers these changes

[Reviewer: Rob] Alarm reliability

---

include/alarm.h

Missed this when making changes to increase alarm reliability in https://github.com/Metaswitch/cpp-common/pull/476

[No Reviewer] Remove clear_all from header file

---

include/diameterstack.h

Moving this to diameterstack.cpp so we can use it in other places. I'll update everywhere that it's currently used too.

Reviewer EM: Add AVPException class

---

src/diameterstack.cpp

This fixes https://github.com/Metaswitch/homestead/issues/328. By the time the Diameter stack is being shutdown, any applications that registered callback handlers should have unregistered them, so we shouldn't unregister them here - we do drop a warning log if we think there is a listener that hasn't unregistered its callback.
I've tested by running (with https://github.com/Metaswitch/homestead/pull/335) against an HSS and restarting Homestead. There is no crash and Homestead shuts down smoothly and quickly.

Reviewer MIRW: Don't unregister callback handler in multiple places

---

src/dnscachedresolver.cpp
test_utils/mockdiameterstack.hpp

Fixes two warnings I saw with Clang 3.8 - sending to you for review as a std::move expert.
* Two of the mockdiameterstack.hpp methods had different signatures to the parent methods. As they weren't used, I've just deleted them.
* Clang told me `moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]` and told me to remove the offending std::move call. I've done so and it seems OK.

[Reviewer: Alex] Fix Clang warnings

---

include/communicationmonitor.h
include/signalhandler.h
include/utils.h
src/utils.cpp

This moves the thread creation out of the signal handler constructors
Fixes #504

[Reviewer: Alex] Move thread creation out of constructor

---

include/signalhandler.h
include/utils.h
src/utils.cpp

Don't make utils.cpp dependent on signal_handler.h

[Reviewer: Graeme] Don't put signal handler stuff in utils

---

include/memcachedstore.h

Part of the fix for https://github.com/Metaswitch/sprout/issues/1428.

Reviewer EM: Create default has_servers method for MemcachedStores

---

include/alarm.h

I think this fixes https://github.com/Metaswitch/cpp-common-test/issues/16 - I ran `LD_LIBRARY_PATH=../usr/lib valgrind --track-origins=yes --malloc-fill=cc --free-fill=df ../build/bin/cpp_common_test_test --gtest_filter="AlarmTest*"` ten times without this fix, and hit that issue four times; I then ran it ten times with this fix and didn't hit it.
I think you added this function originally - it's worth being aware that any time you access a data structure from multiple threads, you need to take a lock, even if you're clearing it - I suspect the issue was that one thread was trying to access elements of the vector that other threads had cleared, and corrupted some other memory when it did so.

[Reviewer: Andrew] Take lock when clearing alarm list

---

src/diameterstack.cpp

`fd_msg_sess_get` can return 0, to indicate successful completion, but still set the session to NULL (see https://github.com/Metaswitch/freeDiameter/blob/33bdebe6674f3d98ce7b9d6e8d52db934914820d/libfdproto/messages.c#L1518). This PR checks for that case, and doesn't try to do anything with the session.
This caused https://github.com/Metaswitch/freeDiameter/issues/21 (although we no longer hit that issue, normally, as we've stopped SAS logging Device-Watchdog-Requests and therefore stopped going through this code path).

[Reviewer: Graeme] Don't call fd_sess_getsid on NULL

---

include/alarm.h
src/alarm.cpp
test_utils/mockalarm.h
test_utils/mockcommunicationmonitor.h

Rob, can you please review this change to the alarm classes.
This PR covers:
* Renaming the AlarmManager to the AlarmReRaiser
* Stopping the AlarmReqAgent and AlarmReRaiser from being singletons
* Adding a new AlarmManager that's responsible for the AlarmReqAgent and the AlarmManager (i.e. making sure they're created/deleted safely).
* Simplifying the re raising alarm function
This PR doesn't cover any change to the AlarmReqAgent/AlarmReRaiser (beyond simplifying the reraise function)
Fixes #521

[Reviewer: Rob] Fix for alarm crashes

---

test_utils/test_snmp.h

Make `snmp_get_raw` print OIDs numerically. I've checked that clearwater-fv-test and the alarm agents tests still work.

[No review required] Call snmpget such that OIDs are printed numerically

---

include/alarm.h
src/alarm.cpp

I think the crash you hit when we tried a version of this code last week might have been due to not saving off the `alarm_manager` constructor argument - that seems like a possible thing not to do, and if I comment out that line, I also hit a crash at the same point.

[Reviewer: Graeme] Add unregister_alarm call in alarm destructor

---

include/utils.h
src/utils.cpp

Small change to allow daemons to specify the path for stdout and stderr to be used when the daemon process is forked. Also change to append to these files instead of just blasting away the contents.
This is the first half of a fix to Metaswitch/sprout#965.

[Reviewer: Matt W] Allow daemons to provide path for stdout/stderr

---

include/utils.h
src/utils.cpp

There's a bunch of common logging and creation of a daemon which is replicated in every Clearwater server:
This moves a small amount of the common code into cpp-common. It was the largest common set I could move without having to pass function calls to cpp-common to allow the server to hook functions in.

[Reviewer: MIRW] Commonalize logging and daemonization

---

include/snmp_ip_time_based_counter_table.h
src/snmp_ip_time_based_counter_table.cpp

Instead of ignoring add methods that occur when a row already exists,
keep track of them, and only remove a row when the same number have
occurred.
I've got an additional FV test in https://github.com/Metaswitch/clearwater-fv-test/pull/48

[Reviewer: Alex] Reference count rows of the IP time counter table

---

include/alarmdefinition.h
include/json_alarms.h
src/json_alarms.cpp

The big changes here include:
- Updating the JSON parser to read the new fields, do some validity checking on them and then assign them to the new member variables of the SeverityDetails and AlarmDefinition structs.
- Adding methods to the AlarmTableDef class to retrieve the new values in the above structs (that are part of the AlarmTableDef object) and tests these get parsed correctly by the JSON parser. https://github.com/Metaswitch/clearwater-snmp-handlers/pull/157
- Testing that the JSON parser rejects JSON fields that are too long. https://github.com/Metaswitch/cpp-common-test/pull/26
- Updating the Python JSON parser to test that the new enterprise MIB fields are under 4096 characters. https://github.com/Metaswitch/python-common/pull/64
Notes:
- The way I've done the alarm name …

[Reviewer: Ellie] Adds support for enterprise alarms MIB

---

src/httpconnection.cpp

As you pointed out, the calculated HTTP connection latency is actually only half of the total time (as it doesn't include the retry).  The comment at the top of httpconnection.cpp is misleading - this fixes it.

[Reviewer: Ellie] Clarify latency comment in HttpConnection

---

src/baseresolver.cpp

Modify BaseResolver so that strings required for debug logging are created only when debug logging is switched on; unnecessarily creating these strings was causing a performance hit.

[Reviewer: RKD] Modify debug string creation to improve performance

---

include/diameterstack.h
src/diameterstack.cpp

Graeme,
As discussed, the current experimental result API on a Diameter Message only returns the experimental result code, as opposed to also including the vendor ID.
As experimental result codes are scoped by vendor ID, we should also include the vendor ID in the response - a better name for 'Experimental Result' would be 'Vendor Specific Result' I think.
Note, that the vendor ID may differ between the VENDOR_SPECIFIC_APPLICATION_ID and the EXPERIMENTAL_RESULT AVPs - although I suspect that's in practice not very likely - so the existing call to vendor_id() is not appropriate here.
As such, I've changed cpp-common to have a experimental_result function which will provide the code and the vendor ID of the first Experimental Result found, returning true if found, and false otherwise. It …

[Reviewer: GDR] Experimental Result Codes must be scoped by vendor

---

include/http_connection_pool.h
src/http_connection_pool.cpp

The maximum idle time for a HTTP connection in the connection pool is passed into the connection pool constructor in milliseconds, but the constructor expects it in seconds. This pull request fixes this, changing the maximum idle time to seconds.

Fix unit discrepancy

---

test_utils/test_interposer.cpp
test_utils/test_interposer.hpp

I've verified that using this at least fixes the first failure detailed in https://github.com/Metaswitch/clearwater-fv-test/issues/41.

Reviewer RKD: Allow cwtest_completely_control_time to set time to start of epoch

---

include/sasevent.h

Updated the Resource bundle number, to that which includes the new failover logs.

BGCF-12 Updating SAS Resource bundle version number for failover logs.

---

src/snmp_success_fail_count_by_request_type_table.cpp
src/snmp_success_fail_count_table.cpp

Only weird thing here is that we report percentages in units of 10,000 of a percent to maintain accuracy whilst still using integers.

[Reviewer: Ellie] Changes success percent stats to report 100% when there are no errors

---

include/cassandra_store.h
include/httpclient.h
include/httpstack.h
src/cassandra_store.cpp
src/httpstack.cpp
test_utils/cass_test_utils.h
test_utils/mock_cassandra_store.h
test_utils/mockhttpstack.hpp

Graeme, please can you review these changes to implement the cached data API. This consists of the following changes:
* HttpStack: allow a process can have multiple instances of it and enhance it to allow binding to a unix socket (includes some reworking of its API to allow this). 
* CassandraStore: allow clients to call the `get_range_slices` method to iterate over keys. 
Tested as part of https://github.com/Metaswitch/homestead/pull/375 and https://github.com/Metaswitch/sprout/pull/1559

[Reviewer: GDR] HttpStack and CassandraStore changes for the cached data API

---

include/cpp_common_pd_definitions.h
include/dnscachedresolver.h
include/signalhandler.h
src/dnscachedresolver.cpp
src/signalhandler.cpp

- constructors now take an optional filename
- it will try to read this as a JSON file, storing the static records in memory
- when doing a dns_query, these records will be examined first.
Currently, only CNAME records are supported
- if one is found, the DNS query is performed on the redirected host rather than the original
Testing done:
- UTs (in cpp-common-test)
- some live testing (though more will follow)

[Reviewer: Ellie] Allow DnsCachedResolver to load static DNS records

---

include/load_monitor.h
include/snmp_abstract_continuous_accumulator_table.h
include/snmp_abstract_scalar.h
include/snmp_continuous_accumulator_by_scope_table.h
include/snmp_continuous_accumulator_table.h
include/snmp_counter_by_scope_table.h
include/snmp_event_accumulator_by_scope_table.h
include/snmp_internal/snmp_scope_table.h
include/snmp_internal/snmp_time_period_and_scope_table.h
include/snmp_scalar_by_scope_table.h
include/snmp_statistics_structures.h
src/load_monitor.cpp
src/snmp_continuous_accumulator_by_scope_table.cpp
src/snmp_counter_by_scope_table.cpp
src/snmp_event_accumulator_by_scope_table.cpp
src/snmp_scalar.cpp
src/snmp_scalar_by_scope_table.cpp

This adds two new tables that are indexed by time period and scope (node type):
`EventAccumulatorByScopeTable`
`CounterByScopeTable`
These depend on the new time and scope based row:
`TimeAndScopeBasedRow`
See the sprout pull request for the testing that I've done.

[Reviewer: RJW2] Add scope indexed SNMP tables

---

include/connection_pool.h
src/cassandra_connection_pool.cpp
test_utils/testable_connection_pool.h

If the cassandra process goes down and comes back up, connections to that
process are no longer valid and should be torn down and recreated.
So this commit adds a member variable to the connection pool. If true, when a
connection is released but marked not to be returned to the pool, then all
existing connections in the pool for the same target are destroyed too.
This is false by default, and only true for the CassandraConnectionPool. This
means that when one bad Cassandra connection is found, the others are
proactively destroyed.
**Testing done**
- UTs (see the cpp-common-test branch)
- live tests

[Reviewer: Ellie] Cassandra Connection pool changes

---

include/sasevent.h

SAS resource bundle has been updated with a new datestamp, changing sasevent.h to use this new datestamp.

[Reviewer: CJR] Update to datestamp for SAS resource bundle

---

src/cassandra_connection_pool.cpp

This increases the Cassandra timeouts. 
Tested live.
Fix for issue https://github.com/Metaswitch/homestead/issues/387

[Reviewer: Seb] Change timeouts

---

include/sasevent.h

Remove SAS base for timberlake from sasevents.h.

Remove timberlake from SAS events header file

---

src/httpstack.cpp

Not really a bug fix, but these modifications make it a lot clearer what happens when proxied_sas_logger receives a request with an x-real-ip header, but missing an x-real-port header. 
The previous implementation relied on the default value of shorts being 0, which works, but hides what the error handling is doing.

Made the error cases in get_x_real_ip_port clearer

---

include/httpconnection.h
src/httpconnection.cpp

This path variable can contain the path, query and fragment parts, so it is more correct to call it the url_tail.

[Reviewer: AJH] Rename path to url_tail

---

src/snmp_continuous_increment_table.cpp
src/snmp_infinite_scalar_table.cpp
src/snmp_infinite_timer_count_table.cpp
src/timer_counter.cpp

All the areas we discussed, and rested with locks, are now using atomic functions to ensure we set the right value, or re-do the calculation with a new starting point.
In the continuous increment table, to do this, I have moved where we set the new value for `current_value` up to before all of the average, sum etc. calculations, which occur at the top of `accumulate_internal`. This means that they will be calculated using the new `current_value` rather than the old `current_value`. 
I'm not sure if this is a big issue for the statistics, are you able to comment at all on that?
In testing, this now appears to resolve the three Chronos stats issues:
https://github.com/Metaswitch/chronos/issues/328
https://github.com/Metaswitch/chronos/issues/329 …

[Reviewer: Matt] Thread safer stats

---

include/json_alarms.h
src/json_alarms.cpp

Fixes https://github.com/Metaswitch/clearwater-snmp-handlers/issues/167
Since I'm recirculating the MIBs spec and updating the docs to fix https://github.com/Metaswitch/clearwater-snmp-handlers/issues/170, it seemed efficient to do this too.

[Reviewer: Ellie] Don't convert alarm names to title case

---

src/snmp_agent.cpp

Write the persistent SNMP file to somewhere Sprout can write to. We don't actually use this - but we get errors logs on shutdown for the current location. Fixes https://github.com/Metaswitch/sprout/issues/1475. Tested live

[Reviewer: Adam] Set persistent file somewhere that the cpp process can write to

---

include/cpp_common_pd_definitions.h
src/realmmanager.cpp

Remove an ENT log as it doesn't provide any information that isn't more helpfully provided by the communication monitor. Fixes issue https://github.com/Metaswitch/homestead/issues/410.

[No reviewer] Remove unnecessary ENT log

---

include/sasevent.h

Merge updated SAS datestamp into release-114-fixes, for Metaswitch/clearwater-sas-resources#130
This merge is being done while in dev/master code freeze, so it will not be merged into dev/master at this time. cpp-common references will be updated on release-114-fixes only until the code is unfrozen

[No reviewer] Update sas datestamp in release-114-fixes

---

include/sasevent.h

No reviewer, as this is a datestamp change.
Updating datestamp for Metaswitch/clearwater-sas-resources#132. Both this PR and the linked PR will be merged into both release-114-fixes and master.

Update SAS datestamp to 20170203

---

src/diameterstack.cpp

Graeme,
Please can you review this fix to https://github.com/Metaswitch/homestead/issues/392?  Basically, the pmd structure can be NULL, so we should avoid dereferencing it if so.  We also TRC_WARNING so that we can track this - it should happen very rarely - if it starts happening frequently, we may have uncorrelated SAS trails.
UTs pass.  I'm just kicking the tyres live.
The other tidy-ups are to misleading/imprecise trace statements and superfluous blank lines.
Matt

[Reviewer: Graeme] Be tolerant to not finding per-message data (e.g. in error scenarios)

---

src/httpstack.cpp

Add a comment to warn that the HttpStack should only be started once a socket is bound

HttpStack comment

---

include/httpclient.h
include/httpconnection.h
include/httpstack.h
src/httpclient.cpp
src/httpstack.cpp
test_utils/fakecurl.cpp

Makes changes to the HttpStack and the HttpClient so that the bodies of Http requests and responses can be optionally obscured in SAS:
- ProxiedSasLogger (which is currently only used by Bifrost) is replaced with ProxiedPrivateSasLogger which doesn't log any bodies to SAS.
- A 'should_omit_body' variable is added to HttpClient which defaults to false. If enabled, then http bodies are again obscured when being reported to SAS.

Optionally obscure Http bodies in SAS logs

---

include/httpstack.h
src/httpstack.cpp

As per my email, this is to separate the part of the SAS logger which obscures the bodies of requests from the part that sits behind a reverse proxy.

Separate PrivateSasLogger from ProxiedPrivateSasLogger

---

src/httpclient.cpp

When we get a curl timeout on an HTTP request, we should report the HTTP return code as 503.
This allows the upstream node to handle the timeout correctly.
This is a fix for issue https://github.com/Metaswitch/sprout/issues/1623
- live tested by manually dropping packets to Homestead, and verifying that Sprout correctly interprets that as an HTTP 503
- verified live tests still pass on a deployment with this fix

[Reviewer: Adam] Return HTTP 503 on curl timeout

---

src/dnscachedresolver.cpp
src/httpclient.cpp

Specifically, failure to contact external HTTP or DNS servers

Soften some errors to warnings

---

src/alarm.cpp

This pull request fixes https://github.com/Metaswitch/stats-engine/issues/434. In this issue AME2 reported a periodical log spam every 30 seconds writing out logs like 
```
21-02-2017 14:39:35.623 UTC Status alarm.cpp:62: statistics engine issued 10001.1 alarm
21-02-2017 14:39:35.623 UTC Status alarm.cpp:62: statistics engine issued 10002.1 alarm
21-02-2017 14:39:35.623 UTC Status alarm.cpp:62: stats-engine issued 10003.1 alarm
21-02-2017 14:39:35.623 UTC Status alarm.cpp:62: stats-engine issued 10004.1 alarm
21-02-2017 14:39:35.623 UTC Status alarm.cpp:62: stats-engine issued 10007.1 alarm
21-02-2017 14:40:05.623 UTC Status alarm.cpp:62: statistics engine issued 10001.1 alarm
21-02-2017 14:40:05.623 UTC Status alarm.cpp:62: statistics engine issued 10002.1 alarm
21-02-2017 14:40:05.623 …
```

Change log level of reraising alarms log and add more logging

---

include/dnscachedresolver.h
include/sasevent.h
src/dnscachedresolver.cpp

Hi Ellie
Can you review this package of DNS timeout changes (I've discussed with MIRW)?   They are
- Changing the default timeout for a query to 200, and adding the facility to override this
- Adding a SAS log for when a timeout fails (at the moment, we only see a timeout log if _all_ DNS servers fail, so if multiple DNS servers are configured and only one is offline, we don't notice anything in SAS other than a time jump in the SAS logs). 
-  Changing "tries" in the ares_init_options back to 1.  Rob explicitly set this to "server_count" in https://github.com/Metaswitch/cpp-common/pull/243/files#diff-b76e44fc3db821f376c4d58277322bc6L691, but I don't think this makes sense - the ARES docs explicitly say that "tries" is the number of tries per server, not overall. I don't think we want more …

[Reviewer EM] Improve DNS behaviour in the event of server failure

---

include/localstore.h
src/localstore.cpp

Some enhancements to the local store class we us in UTs to allow it to fail get requests. Needed for https://github.com/Metaswitch/sprout/pull/1823

Enhance the local store to allow failures when getting data

---

include/cassandra_store.h
include/sasevent.h
src/cassandra_store.cpp
src/memcachedstore.cpp

This is a fix to alleviate issue: https://github.com/Metaswitch/clearwater-issues/issues/95
For our cassandra read requests, we try Consistency Level TWO first, and then Consistency Level ONE if that fails.
Previously, we would do this for each Cassandra node that we tried to contact. This meant that, in the scenario where we have 2 Cassandra nodes, A and B, and A is being too slow to respond to our request, we would have done:
- TWO request to A, which times out
- ONE request to A, which times out
- TWO request to B, which times out
- ONE request to B, which succeeds
Although this eventually succeeds, we've taken a long time to establish that the TWO requests didn't work. In the case of Homestead talking to Cassandra, Sprout would have already timed out the request.
Therefore, if we fail …

[Reviewer: Adam] Cassandra fixes

---

test_utils/mockhttpconnection.h

Extend mockhttpconnection.h to include a mocked-out send_get method.
Also change argument name in existing mocked-out send_post method to reflect the interface as defined in include/httpconnection.h

Extend mockhttpconnection to include send_get method.

---

src/httpstack.cpp

@AlexHockey please let me know if you're not the right person to take this.
This addresses a potential vulnerability in libevhtp. After initialising the stack, we set a 20s read timeout. Closure of the vulnerability has been tested by running nmap: after applying this fix, the issue is not flagged.

[Reviewer: AJH] Add 20s HTTP request read timeout

---

include/sasevent.h
src/httpclient.cpp

The log at the end of `HttpClient::send_request` is all kinds of wrong. 
* It contains little useful information about what was going on that might have caused the problem.
* It can be generated when there wasn't a cURL error.
* It can be generated when cURL wasn't even invoked (e.g. when DNS failed to resolve).
* It shouldn't even be a log - it should be a SAS event instead. 
This PR fixes these issues by removing the log and replacing it with a SAS log covering the scenario when the hostname does not resolve.

Replace a duff engineering log with a SAS log

---

src/httpclient.cpp

Two changes:
* We increment attempts whenever we try to contact an  HTTP server. 
* Unescape the URL before logging to SAS. 
Tested as follows:
* REGISTER with the homestead hostname configured correctly. 
* REGISTER with the hostname mis-configured (so it does not resolve). 
* REGISTER with homestead not running (hopefully proves the change from for loop -> while loop hasn't broken the world). 
Unit test code incoming.

Fix bugs in SAS logging when HTTP DNS name does not resolve to anything

---

include/event_statistic_accumulator.h
include/snmp_internal/snmp_time_period_and_string_table.h
include/snmp_time_and_string_based_event_table.h
src/event_statistic_accumulator.cpp
src/snmp_event_accumulator_by_scope_table.cpp
src/snmp_event_accumulator_table.cpp
src/snmp_time_and_string_based_event_table.cpp
test_utils/test_snmp.h

Add support for string and time indexed event stats.   We're going to need these in order to expose per AS latency stats in the S-CSCF.
Tested by https://github.com/Metaswitch/clearwater-fv-test/pull/56

Add support for string and time indexed event stats

---

include/httpstack.h

Remove the `url_unescape` function in httpstack.h and use the one in the Utils class instead.

[Reviewer: AJH] Use correct URL unescape function

---

include/baseresolver.h
src/a_record_resolver.cpp
src/baseresolver.cpp

Goes along with Metaswitch/sprout#1891. I will be opening the cpp-common-test PR shortly, which includes the unit tests for this change.
Interesting things to note:
* The constants defining the allowed host states had to be defined as `static`. Furthermore, I chose to define them as `constexpr` instead of `const` - this implies both `inline` and `const` for the static variable, so they are evaluated at compile time. I saw no downside in doing this, but please shout if you disagree.
* As discussed in the Sprout PR - I felt that it was appropriate to add a helper function (`get_allowed_host_states`) which takes the `allowed_host_state` bit and sets two bool references to indicate which host states were allowed, instead of performing a bitwise check every single time we want to evaluate this …

[Reviewer: HJS] 'Allowed host state' interface change and implementation for DNS resolvers

---

include/pdlog.h

Marks these ID ranges as reserved so that nobody else will use them.

[Reviewer: HJS] Reserve some PDLog ID ranges

---

include/http_connection_pool.h
include/httpclient.h
src/http_connection_pool.cpp
src/httpclient.cpp
test_utils/curl_interposer.cpp
test_utils/fakecurl.cpp
test_utils/fakecurl.hpp

Alex, are you OK to review this?  Its part of the fix for this "send provisioning traffic over the signaling interface" enhancement we discussed the other day.
The change I had to make to cpp-common here was to add a CURL timeout override to HttpClient.  I've tested this live and checked that the timeout is applied if that new parameter is passed.
I've also updated cpp-common-test (PR coming up)

[Reviewer AJH] Add timeout override to HttpClient

---

test_utils/test_interposer.cpp

If start_of_epoch is specified, we should set the time to 0

[Reviewer: Richard] Fix cwtest_completely_control_time

---

include/httpclient.h
include/httpconnection.h
src/httpclient.cpp

This PR give us the ability to log a different server address to the SAS call flow, than the actual address in the HTTP request.  An example use case is when sending requests to localhost, where we may wish to instead log the public/private IP of the node in SAS
I don't think that the arguments I have added to the constructor necessarily belong at the end, but I have added them at the end to ensure this is a non-breaking change for existing uses of these classes.
I have tested this on my deployment and run the live test suite, and `make full_test` passes in Sprout

[Reviewer=CJR, KH1] Add ability to customize the server details we send to SAS

---

include/baseresolver.h
include/utils.h
src/a_record_resolver.cpp
src/astaire_resolver.cpp
src/baseresolver.cpp
src/diameterresolver.cpp
src/httpclient.cpp
src/memcached_connection_pool.cpp
src/utils.cpp
test_utils/fakehttpresolver.hpp

Now that I'm adding connection pooling to astaire, I've moved the code to disable Nagle's algorithm into the memcached connection pool code. I think this is ok because of the last part of the comment which says "libmemcached's buffers are large enough that it will never send small message fragments, and this store's implementation means we very rarely pipeline requests".
I've also tidied up some other code:
- I've moved `parse_ip_target()` from the Baseresolver to Utils since that's where all the other address parsing utility functions live. It also means I don't need to include baseresolver.h to use this function.
- We have 3 implementations of a function to turn an AddrInfo into a string. I've consolidated all this in the AddrInfo class and will be deleting the other functions.

[Reviewer: AJH] Disable Nagle's algorithm in memcached

---

include/sasevent.h

Add a comment to the resource bundle datestamp line, making it clear what needs to be updated if you ever do need to change this value by hand.  This should help to avoid issues where we ship releases in which different components depend on different SAS resource bundles.

Add resource bundle comment

---

src/namespace_hop.cpp

Also add additional logging so that namespace hop connection failures can be debugged
The code as written fails to perform a namespace hop if the length of the path is something other than 8 bytes (7 characters + a null terminator).
This is because it compares sizeof(socket_factory_path) is always 8 bytes on a system with 64 bit pointers (because it's a char*, not a char[108] like addr.sun_path), which means we only copy the first 8 bytes of the path into `addr.sun_path` which means the connect call fails with `No such file or directory`.
I've added a bunch of logs which I used to debug the problem.

[Reviewer: Ellie] Correctly determine the length of the socket file

---

test_utils/mockdiameterstack.cpp
test_utils/mockdiameterstack.hpp
test_utils/mockhttpstack.cpp
test_utils/mockhttpstack.hpp

For background see out of date PR: https://github.com/Metaswitch/homestead/pull/150

Move mock constructors / destructors out of headers

---

include/connection_pool.h

Creating and destroying connections takes an unknown amount of time, so we must
never do them behind the connection pool's lock
Specifically, memcached connections require actually connecting to the memcached server when created. When talking to a remote site, this may take up to 200ms, so we really can't do this behind the lock.
This is a fix for: https://github.com/Metaswitch/clearwater-issues/issues/2413

[Reviewer: Richard] Don't do unnecessary work behind the connection pool lock

---

include/localstore.h
include/memcachedstore.h
src/localstore.cpp

Seb,
When the Sprout UTs directly call through to the local store, they use a LocalStore* pointer, rather than a Store*.
Due to a feature in C++, called name hiding, which is invoked because when of the methods is override, the other argument overload for the function is hidden. This means that the code defaults to a different overload of the method, which means we end up using the CAS value as the expiry, which means that the data expires immediately.
I've fixed this by:
- Overriding the name hiding by asking to import the names into the derived classes.
- Renaming the inner function to avoid it being picked up accidentally.
I've verified the failing test now passes.

[Reviewer: Seb] Fix issues arising from name hiding

---

include/httpclient.h
include/httpconnection.h
src/httpclient.cpp

Mat,
This resolves a bug we've seen whereby we always add a Content-Type header.
This was originally the case (see https://github.com/Metaswitch/cpp-common/blob/11222e20d4fe50adb17b6fb3db05a3937f01a800/src/httpconnection.cpp#L495-L499 ) but got lost in some refactoring.

[Reviewer: Mat] Only add a Content-Type header if we have a body

---

src/localstore.cpp

flush_all wasn't actually flushing all. Now it does.

[Reviewer Richard] Clear out old_db on flush_all too

---

src/log.cpp

Alex,
As discussed, it'd be nice to have the thread ID in engineering log files.
This adds it using `pthread_self()` which shouldn't have a significant performance hit to run.
Sample log line is:
`17-10-2017 18:32:10.141 UTC [7fb8035f3700] Debug alarm.cpp:408: AlarmReqAgent: servicing request queue`

[Reviewer: Alex] Include the thread ID in logs

---

include/httpstack.h
include/sasevent.h
src/httpstack.cpp
src/httpstack_utils.cpp

Quicksilver microservices are expected to use X-Span-Id for correlating SAS trails. This PR adds support for logging this in clearwater components, if present on an inbound request.
See https://github.com/Metaswitch/cpp-common-test/pull/71 for the corresponding PR to cpp-common-test

Added support for using X-Span-Id as a SAS correlation header

---

src/load_monitor.cpp

A few tweaks to the load monitor logs:
- Change logs related to latency and refill rate calculation to be info level (so they are not written out by default). 
- Print the current refill rate out in the "rate unchanged" log. This is useful when analyzing the behavior of the load monitor. 
- Make one of the logs more user friendly.

Update load monitor logs

---

src/memcached_connection_pool.cpp
src/memcachedstore.cpp

This resolves two places which we didn't consider IO operations, and thus didn't call the IO hooks.
- `memcached_server_add()` This will attempt to connect to the server over TCP, as memcached has it's own connection management code. Thus, in a high latency deployment, this can take > 100ms.
- `memcached_fetch_result()`. While `memcached_mget()`, is responsible for performing a GET, fetch result is responsible for waiting for that get to actually be available. This thus means that it will block waiting for the other end.
I've tested this live

[Reviewer: Alex] Consider time waiting for memcached as IO time

---

include/snmp_agent.h
include/snmp_internal/snmp_table.h
src/snmp_agent.cpp

Rich,
Please can you review this fix to a window condition in which a Clearwater worker thread adds/removes a row to/from Net-SNMP while a Net-SNMP agent thread is accessing it?
The fix is to put a lock around Net-SNMP's operations.
To keep this all tidy, I've pulled the SNMP agent function into a class (so that it can own its variables).  I have, however, kept the start-up methods, to ensure all existing code continues to work.
I've stress-testes with simultaneous SIP and SNMP traffic and not seen any issues.  I can't be sure the crash I saw before is fixed without a whole load more stress, but I'm hoping to be able to run that in the background over the next few weeks.
Matt

[Reviewer: Rich] Lock around Net-SNMP calls

---

src/snmp_agent.cpp

Not sure why I didn't hit this during my testing, and a shame that it isn't covered by https://linux.die.net/man/3/snmp_select_info, but we need to process alarms too.
I've done a review against `agent_check_and_process` and
*   also added `netsnmp_check_outstanding_agent_requests`, although I don't think we use it
*   not added `snmp_store_if_needed` because we definitely don't use that.
Please can you review?

[Reviewer: Rich] Process alarms

---

src/dnscachedresolver.cpp

Currently we don't treat DNS requests as IO operations, which means that they can cause requests to erroneously be regarded as being slow on a process (e.g. on Sprout), which can cause incorrect overload behaviour.
There's two changes here:
- The first is relatively uncontroversial I think - waiting for DNS query replies, we treat as an IO operation.
- The second is more controversial, but I think it's the right think to do - we treat waiting for another thread to complete when it's performing an outstanding IO operation, as an IO operation. I think this is more controversial, but I think the reasoning is sound - essentially that other thread is acting as a blocking IO call for this thread, and thus it's right for this thread to block based on it. This is much rarer - as the DNS operation …

[Reviewer: Alex] Treat DNS requests as IO

---

include/sip_event_priority.h
include/snmp_internal/snmp_counts_by_other_type_and_scope_table.h
include/snmp_internal/snmp_time_period_other_type_and_scope_table.h
include/snmp_success_fail_count_by_priority_and_scope_table.h
src/snmp_success_fail_count_by_priority_and_scope_table.cpp

Adds a new SNMP table that covers tracks attempts/successes/failures of events put on the queue for worker threads by priority level.

[Reviewer: KH1] Add table for queue success/fail by priority

---

include/threadpool.h

Allows the ThreadPool to optionally take an `SNMP::EventAccumulatorByScopeTable` in its contructor.
If provided, it accumulates the queue size each time it adds work to the queue.
Counterpart to https://github.com/Metaswitch/homestead/pull/497

[Reviewer: Richard] Thread pool queue stat

---

include/exception_handler.h
include/log.h
include/logger.h
src/exception_handler.cpp
src/log.cpp
src/logger.cpp

Hi Ellie, please can you review this PR that makes our exception handling behavior more robust? 
Prior to these changes, every time we hit a handled exception we:
* Dumped a core file.
* Logged basic stack trace to the log file.
* Logged advanced stack trace to the log file. 
I've changed this so that we:
* Dump a core file on the **first** handled exception. 
* Log basic stack trace to the log file. 
* Log advanced stack trace for the **first** handled exception. This comes with some restrictions:
* It is generated from the core dumping process (which means we only get the stack from the trace that hit the exception). This was necessary to avoid stopping the sprout process while generating the trace. 
* Advanced stack trace is now logged to stderr (which gets captured to a log file). …

Make exception handling more robust

---

include/load_monitor.h
src/load_monitor.cpp
test_utils/mockloadmonitor.hpp

This adds a method to the load monitor to allow all requests to cost a token, but have certain requests be allowed anyway even if there aren't any tokens.
This also smoothes out the latency calculations so that the average latency is calculated from the requests that make up the 20 requests before a recalculation.
Tested in UTs, and shortly under overload.

[Reviewer: Sathiyan] Have all requests cost a token

---

include/httpclient.h
src/httpclient.cpp

Mat,
We've been seeing a bunch of HTTP connection errors (most of which are mitigated by https://github.com/Metaswitch/curl/pull/2). This commits the extra logging that I've been using to diagnose the failures, which I think is generally useful:
- Include error message from libcurl in the warning log, and the SAS log if
it's available.
- Include time the HTTP request was sent in the log, to debug timeout
errors.

[Reviewer: Mat] Improve HTTP error messages

---

include/utils.h
src/utils.cpp

Hi Richard.
This is the "quote string" utility function that I wrote alongside the CF quoting function (see https://github.com/Metaswitch/sprout/pull/2042).

[Reviewer RJW2] Quote utility function

---

include/httpclient.h
include/httpconnection.h
src/httpclient.cpp
src/httpconnection.cpp

Required for Bifrost Twilio integration.  Added following the same pattern elsewhere in httpclient/httpconnection.

Add POST method which can take extra headers on the outbound request

---

include/localstore.h
include/memcachedstore.h
include/store.h
src/localstore.cpp
src/memcachedstore.cpp
test_utils/mock_store.h

Add parameter to allow caller to specify the format of data being added/retrieved from memcached for use when logging to SAS.

[Reviewer: AJH] Allow format parameter for SAS logging of memcached requests

---

src/snmp_agent.cpp
test_utils/test_snmp.h

Alex,
Please can you review this fix to clearwater-fv-test (and any other SNMPTest-using suites)?  As discussed, I've migrated to use `SNMP::Agent`.
Thanks,
Matt

[Reviewer: Alex] Fix clearwater fv test

---

include/snmp_ip_count_table.h
src/snmp_ip_count_table.cpp

This adds a lock so only one thread can access the IPCountTable at a time.
I've run this through fv-test (SNMPTest.*) branch snmp_threading and it passes all tests. 
(Hit memory leak though:
```
Error: some memory errors have been detected
InvalidRead
InvalidRead
InvalidRead
InvalidRead
InvalidWrite
InvalidWrite
```
)

adding a lock to the IPCountTable

---

include/http_connection_pool.h
include/httpclient.h
include/httpconnection.h
include/memcachedstore.h
src/http_connection_pool.cpp
src/httpclient.cpp
src/memcachedstore.cpp

This PR adds the capability for the user of the HTTP and Memcached clients to specify what IP address the client should establish TCP connections from. This is useful as:
* It allows the FV tests to simulate realistic network conditions such as netsplits and latency. 
* It opens the way for source-based IP routing which might be useful in future. 
Tested by running a simple FV test and checking the network traffic in wireshark.

Specify source address for HTTP and Memcached clients

---

include/chronosconnection.h
src/chronosconnection.cpp

This is needed to allow S4s to use the right address in the FV tests. 
I've tested that this doesn't break anything by running the FV tests. As previously discussed, it would be best to test this against the net split infrastructure we're going to add to the FVs.

Allow the user of a chronos connection to specify an address to connect from

---

include/dnscachedresolver.h
src/dnscachedresolver.cpp

This is needed so that the FV tests can run a DNS server on a non-default port.
As part of this change I've effectively removed this constructor for the resolver. I've done a search on github and I'm fairly confident that the only project using this constructor is the FV tests, which I have fixed up in a separate PR.
```cpp
DnsCachedResolver(const std::string& dns_server, int port, int timeout = DEFAULT_TIMEOUT, const std::string& filename = "");
```

Make the DnsCachedResolver port configurable. 

---

include/log.h
include/saslogger.h
src/log.cpp
src/saslogger.cpp

Refactored from the previous PR [here](https://github.com/Metaswitch/cpp-common/pull/755) to avoid polluting the log infrastructure with SAS knowledge.

[Reviewer: AJH] Common sas_write log callback refactor

---

include/log.h
include/saslogger.h
src/log.cpp
src/saslogger.cpp

Creation of a new logging callback that will be compatible with all sas-clients. 
- saslogger.cpp checks to see if we need to write the received log, and converts the sasclient log level to a string.
- log.cpp writes the sas_ip and log_id if they are present. If not, all the log information will be contained in the msg component, so that will be the only arg written. 
PR for changes to the PC sas-client to interact with the new callback is [here](https://github.com/Metaswitch/sas-client/pull/83).

[Reviewer: AJH] Common sas_write log callback

---

src/diameterstack.cpp
src/httpclient.cpp
src/httpstack.cpp

Changed all instances of `add_compressed_param` to `add_var_param`

[Reviewer: CJR] CPP-Common - Disable Clientside SAS Compression

---

include/dnscachedresolver.h
include/sasevent.h
src/dnscachedresolver.cpp

I'm not going to merge these into master yet, but I've already merged these into sprout's apple_scrumble branch and pushed.
These changes:
* enhance the SAS logs to note when a record was pulled from the DNS cache, and what time and trail ID to use to look for the original query
* add engineering logs (i.e. in /var/log/$COMPONENT/) when:
* we make a DNS query (i.e. actually out on the network, not the local cache)
* we get a DNS timeout
* we get a DNS response
* we successfully parse it
This compiles; I've not, yet, tested live.

[Reviewer: RND] Enhance DNS diagnostics

---

src/http_connection_pool.cpp

This will shortly be covered as part of clearwater-fv-test instead. This is preferable as it allows testing that the functionality actually works rather than just testing to achieve coverage (which is all the UTs can really do). Note I've put "is covered in the FV tests" rather than "will be covered" as otherwise we'll forget to go back and fix the comment. 
Tested by running `make coverage_check` in cpp-common-test. This produced no output and exited with a 0 return code.

Exclude source address code from coverage

---

src/dnscachedresolver.cpp

Revert accidental setting of ARES_FLAG_USEVC, which meant we always did DNS-over-TCP.

Revert DNS-over-TCP change

---

src/httpstack.cpp
src/memcachedstoreview.cpp

This turns down a couple of per log calls which were at too high a level

[Reviewer: SR2] Turns down logs which were too high

---

src/baseresolver.cpp

select_for_probing modifies _hosts, so should be called with the _hosts_lock.
Tested only by running make full_test.

[Reviewer: Sathiyan] Protect a select_for_probing call with the _hosts_lock

---

include/log.h
include/logger.h
src/diameterstack.cpp
src/log.cpp
src/logger.cpp

UTs are in https://github.com/Metaswitch/cpp-common-test/pull/88
This adds a naive RAM buffer which we store logs in from the SIP Stack and Diameter stack (and configurable from everywhere).

Naive RAM Recorder

---

include/cpp_common_pd_definitions.h
src/sasservice.cpp

Adds PDlogs for parsing of invalid sas.json to flag when the on-the-box config file is awrt

Add PDLogs for when the sas.json file is invalid

---

include/diameterstack.h

Changes two private member variables of the `SpawningHandler` to protected, so they can be accessed by derived classes.

[Reviewer: AJH] Change SpawningHandler member access level

---

include/ttlcache.h

This excludes the DNS waiting time from the latency calculations.
This isn't the right way to fix this issue - it's a short term fix.

[Reviewer: Sathiyan] Add more io exclusions

---

include/utils.h
src/io_trap.cpp
src/utils.cpp

This PR contains the infrastructure to check that a process is correctly using the `CW_IO_STARTS` and `CW_IO_COMPLETES` macros. I'm calling this the "IO trap".
The idea is that:
* If a project wants to use the IO trap, it compiles `io_trap.cpp` into a separate shared object. 
* Any threads in that process that must use the `CW_IO_*` macros should call `CW_IO_CALLS_REQUIRED()` before doing any IO. This means the threads will be monitored by the IO trap. 
* When running the process you install the IO trap by using `LD_PRELOAD=/path/to/io_trap.so`.
* If one of the monitored threads does any IO without calling `CW_IO_*` the process will abort (and produce a core file and a stack trace). 
I've tested in sprout by hacking out various calls to `CW_IO_*` calls (specifically in the HTTP client, …

IO Trap Infrastructure. 

---

src/io_trap.cpp

Change to IO traps so that they compile under clang. 
Without this fix you get the following errors, due to the clang implementation of `std::atomic` for a function pointer not auto-dereferencing to the function pointer, which means the call to `()` fails. 
```
/usr/share/clang/scan-build-3.5/c++-analyzer   -MMD -MP -O2 -ggdb3 -std=c++11 -Wall -Werror -fPIC -I../modules/cpp-common/include  -c ../modules/cpp-common/src/io_trap.cpp -o ../build/sprout_io_trap.so/io_trap.o
../modules/cpp-common/src/io_trap.cpp:126:3: error: call to object of type 'std::atomic<FunctionType>' is ambiguous
HANDLE_FD_CALL(recv, sockfd, buf, len, flags);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../modules/cpp-common/src/io_trap.cpp:115:5: note: expanded from macro 'HANDLE_FD_CALL' …
```

[No review required] Make IO traps build under clang
