Metaswitch/cpp-common

- src/cassandra_store.cpp
Fixes https://github.com/Metaswitch/cpp-common/issues/223. Compiles, but not otherwise tested.
> [Reviewer: Ellie] Reduce the log level for Cassandra 'not found' errors

- include/json_parse_utils.h
- include/sasevent.h
- test_utils/mock_store.h
Hi Ellie, please can you review my changes to migrate Sprout's RegStore to using JSON for its records. This PR contains some miscellaneous common and UT code, plus a bump in the SAS resource bundle version.
> [Reviewer: Ellie] Memcached schema upgrade

- include/cassandra_store.h
- include/httpstack_utils.h
- include/threadpool.h
- src/cassandra_store.cpp
- src/httpstack_utils.cpp
Rob, can you review this change to the thread pool as well.
> [Reviewer: Rob] Add in wrapper around thread pool

- src/memcachedstore.cpp
Decrease poll time for memecached
> [Reviewer Andy] Fix for sprout issue #920

- src/logger.cpp
Tedious build warning.  Comments should explain the logic.
> Reviewer Rob - Fix unused varible warning

- include/dnscachedresolver.h
- src/dnscachedresolver.cpp
Counterpart to https://github.com/Metaswitch/sprout/pull/955
> [Reviewer: Ellie] Multiple DNS servers

- include/memcachedstore.h
- src/memcachedstore.cpp
Fixes #38. I have a separate branch that increases the timeout to 100ms for Sprout's remote store.
> [Reviewer: Andy] Configurable memcached latency

- include/sasevent.h
Matches https://github.com/Metaswitch/clearwater-sas-resources/pull/55.
> [No review req'd] Update resource bundle ID

- include/memcachedstoreview.h
- src/memcachedstoreview.cpp
Not yet UTd/regression tested (that's been pushed to next week), but can you please review this change to add the API we previously discussed to the MemcachedStoreView?
> Reviewer Rob - Simple addition of the API

- include/sasevent.h
Andy - can you please merge this with your cpp-common changes
> [Reviewer: Andy] Update bundle date

- include/accumulator.h
- include/baseresolver.h
- include/counter.h
- include/diameterstack.h
- include/health_checker.h
- include/httpstack_utils.h
- src/httpconnection.cpp
These changes stop various build warnings on 14.04
> [Reviewer: Graeme] 14.04 fixes

- src/httpconnection.cpp
Rob, can you review these small tweaks to the HTTP connection start up logs
> [Reviewer: Rob] Expand the HttpConnection start up logs

- include/httpconnection.h
- src/httpconnection.cpp
- test_utils/fakecurl.cpp
- test_utils/mockhttpstack.hpp
Rob, can you review these changes to support new uses of the send_get/send_delete methods
> [Reviewer: Rob] Add in new get/delete options

- src/memcachedstore.cpp
Andy,
Please can you review this change to use a millisecond-accuracy rolling timestamp for the flags field?
Thanks,
Matt
> [Reviewer: Andy] Set flags field to millisecond-accuracy rolling timestamp

- include/realmmanager.h
- src/diameterstack.cpp
- src/realmmanager.cpp
Corresponding change to https://github.com/Metaswitch/homestead/pull/196.
> [Reviewer: Matt] Pass the Diameter hostname to RealmManager along with the realm

- include/utils.h
- src/memcached_config.cpp
Rob, can you please review this fix to strip whitespace from the memcached config file. 
Fixes #273 
Tested live
> [Reviewer: Rob] Iss273

- include/diameterstack.h
- src/diameterstack.cpp
Matt, can you review these changes to add the new diameter routing stats to cpp-common
> [Reviewer: Matt] Add stats

- include/json_parse_utils.h
Extra macros for JSON parsing. Needed as part of https://github.com/Metaswitch/chronos/pull/121
> [Reviewer: Rob] Json parse

- include/baseresolver.h
- include/diameterresolver.h
- include/httpresolver.h
- src/baseresolver.cpp
- src/diameterresolver.cpp
- src/httpconnection.cpp
- src/httpresolver.cpp
- src/realmmanager.cpp
Andy,
Please can you review this fix to make the DNS blacklist duration configurable?  There's no UT for this, but I've tested it live (and it's actually just refactoring).
Matt
> [Reviewer: Andy] Make DNS blacklist duration configurable

- include/alarmdefinition.h
- src/alarmdefinition.cpp
Please review these new alarms.
> Reviewer Rob - Add alarms for etcd and clearwater-live-verification

- src/memcached_config.cpp
- src/memcachedstoreview.cpp
Other part of https://github.com/Metaswitch/sprout/pull/1035.
> [Reviewer: Ellie] Don't crash if we have an empty /etc/clearwater/remote_cluster_settings

- include/sasevent.h
A co-req change that is part of enabling compression of SAS messages in Clearwater
> [No review required] Bump resource bundle version

- src/httpconnection.cpp
Andy, can you review this PR which stops cURL from asking for 100 Continue responses in some situations (which fixes #304). 
Tested live. Here is a before shot:
And here is an after:
> [Reviewer: Andy] Supress 100 Continue responses

- include/cpp_common_pd_definitions.h
- src/httpconnection.cpp
Andy,
Please can you review this fix to https://github.com/Metaswitch/sprout/issues/973?  It doesn't address log spam (which is now covered by #317), but it does improve the log text.
I've tested live.
Thanks,
Matt
> [Reviewer: Andy] Improve ENT log

- include/snmp_internal/snmp_time_period_table.h
> [Reviewer: Ellie] Switch time to REALTIME

- include/utils.h
- src/utils.cpp
Moved this logic in here - is that ok?
> Reviewer AMC: Make xml_escape more efficient

- include/alarm.h
- include/alarmdefinition.h
- include/communicationmonitor.h
- include/memcachedstore.h
- src/alarm.cpp
- src/communicationmonitor.cpp
- src/memcachedstore.cpp
Rob, can you review this change to add a base class to the alarms
> [Reviewer: Rob] Split the alarm code up to make it easy to subclass

- include/snmp_internal/snmp_counts_by_node_type_table.h
- include/snmp_internal/snmp_table.h
- include/snmp_internal/snmp_time_period_and_node_type_table.h
- include/snmp_node_types.h
- include/snmp_single_count_by_node_type_table.h
- src/snmp_ip_count_table.cpp
- src/snmp_single_count_by_node_type_table.cpp
Rob, can you review this change to add a new type of stats table indexed by time and node type. 
Tested live
> [Reviewer: Rob] Add more stats tables

- include/pdlog.h
Minor change to update the ENT log IDs
> [Reviewer: Graeme] Update PD log IDs

- include/cassandra_store.h
- include/sasevent.h
- src/cassandra_store.cpp
Hi Andy,
Would you mind reviewing these changes please?
It has associated changes in homestead (and others). I'll link the pull requests together once the others are created.
Cheers,
Tom
> [Reviewer: Andy] Consistency changes upstream

- src/snmp_single_count_by_node_type_table.cpp
Updated code to match current implementation of get_data()
> [Reviewer: Matt] Updated get_data() method to take parameter

- include/logger.h
- src/logger.cpp
> [No reviewer] Make the _current links relative

- src/diameterstack.cpp
***Not to be merged until corresponding sas-client change has been merged***
I'm also intending to test live before any merging takes place.
> [Reviewer AMC] Add uniqueness scope to Diameter SAS correlator

- src/httpstack.cpp
Rob, can you review this fix to only listen on the local address if we haven't already tried to listen on all. 
Tested live
> [Reviewer: Rob] Allow all in the httpstack

- src/memcached_config.cpp
Alex, can you review this change to hard code the tombstone lifetime?
Fixes https://github.com/Metaswitch/clearwater-etcd/issues/107
> [Reviewer: Alex] Hard code tombstone lifetime

- test_utils/mockhttpconnection.cpp
- test_utils/mockhttpconnection.h
Add basic mock of httpconnection
> [No reviewer] Add mock http connection

- test_utils/fakecurl.cpp
- test_utils/faketransport_udp.cpp
- test_utils/mockhttpstack.hpp
Fixes from running with clang and sanitizers
> Compiler warnings, mostly

- include/health_checker.h
- src/health_checker.cpp
I've been sitting on this fix for a while - this fixes up some of the HealthChecker API issues you flagged ages ago.
> [Reviewer: Andy] Health checker fixes (ready to merge)

- include/alarm.h
- include/httpstack.h
The second commit here claims that code oughtn't to compile, even though it obviously does.  But I think that the compiler is wrong!
> Compiler fixes

- test_utils/mock_infinite_table.cpp
- test_utils/mock_infinite_table.h
Add mock for the infinite table
> [Reviewer: Graeme] Add mock for the infinite table

- src/diameterstack.cpp
Should mean we spot issues like the one you hit a bit more quickly.
> [Reviewer: Chris] Log routing errors at error level, not info

- test_utils/mock_chronos_connection.cpp
- test_utils/mock_chronos_connection.h
Add a new ChronosConnection Mock
> [Reviewer: Rob] Add Chronos mock that doesn't just accept everything

- include/snmp_infinite_base_table.h
- include/snmp_infinite_scalar_table.h
- include/snmp_internal/snmp_table.h
- src/snmp_agent.cpp
- src/snmp_infinite_base_table.cpp
- src/snmp_infinite_scalar_table.cpp
- src/snmp_infinite_timer_count_table.cpp
- test_utils/mock_scalar_table.cpp
- test_utils/mock_scalar_table.h
Tested on a single node system and all looks good. 
Going to test further on multi-node system, but i don't think my code will had any effect on that, so should all be good. Would be good if you can check i haven't done anything stupid in the structure of header files.
Other than adding "InfiniteBaseTable::" to function names, i don't believe i've touched anything other than: increment decrement functionality, get_value function, max_row and max_column, and the maps the data is stored in in the child classes.
> [Reviewer: Andy] Scalar infinite table

- src/memcachedstore.cpp
Change the `TopologyNeutralMemcachedStore` accordingly.
> [Reviewer: Rob] Astaire uses port 11311

- src/load_monitor.cpp
I also updated a log while debugging this, to say "handled 3 requests in last 2006ms" instead of "handled 3 requests recently" - that's a change worth keeping.
> [Reviewer: Andy] Divide nanoseconds by 1,000,000 to get milliseconds

- include/alarmdefinition.h
- include/pdlog.h
Adds the PDlog and Alarm values for the new queue manager
> [Reviewer: Andy] Add PD and alarm values for the queue manager

- include/sasevent.h
SAS bug has been fixed so we can use a new resource bundle.
Alex - here is the other half of the fix.
> [Reviewer AJH] Update to resource bundle for fix to SFR477136.

- include/memcachedstore.h
- src/memcachedstore.cpp
This PR refactors out some duplicated code from the topology-neutral store:
* Moves construction of the fully-qualified key into one place. 
* Commonalizes the loop-over-targets code into one place, but with the actual communication to memcached done from within a lambda. 
Thoughts?
Tested in the FV tests.
> [Reviewer: Andy] Refactor duplicated code out of the topology-neutral store

- src/json_alarms.cpp
Fixes https://github.com/Metaswitch/clearwater-etcd/issues/214
> [Reviewer: Rob] iss214: Adds comment explaning alarm state->severity mapping

- include/communicationmonitor.h
- include/cpp_common_pd_definitions.h
- src/communicationmonitor.cpp
updates communication monitor to handle alarms and logs better.
> [No Reviewer] Communication monitor updates

- include/base64.h
- src/base64.cpp
Hi Andy,
This is the cpp common change to go with the following:
* https://github.com/Metaswitch/homestead/pull/297
* https://github.com/Metaswitch/sprout/pull/1309
Please could you review?
> [Reviewer Andy] Add wrapper to encode strings

- include/cpp_common_pd_definitions.h
Just altering the wording of a PD-LOG
> [No reviewer] updated pd_log text

- include/chronosconnection.h
- src/chronosconnection.cpp
- test_utils/mock_chronos_connection.h
Enabling use of the new Chronos API for tags
> [No Reviewer] Stats api update

- include/alarm.h
- src/alarm.cpp
The main changes here involve changes made to the alarm class hierarchy and creating functions to reraise the alarms every 30 seconds.
> [Reviewer: Chris] Resend status of alarms to alarm handler- cpp-common

- include/store.h
- src/localstore.cpp
As discussed, bring store implementations into line for expiry of 0, settling on MemcachedStore's behaviour.
I don't think this will break anything and I've run the Ralf and Sprout UTs successfully. Jenkins will do the rest.
> Reviewer AMC: Expire data if it expires now

- include/diameterstack.h
Check out this little gem I came up with all by myself.
Live testing now.
> Reviewer AMC: Expose method for creating message with specific application

- src/baseresolver.cpp
- src/httpstack.cpp
- src/logger.cpp
- src/memcachedstoreview.cpp
Part of the fix for https://github.com/Metaswitch/cpp-common-test/issues/3.
> [No reviewer] LCOV where appropriate

- include/pdlog.h
Co-req change needed for the UTs in https://github.com/Metaswitch/sprout/pull/1358
> [Reviewer: Rob] Allow logs to be mocked

- include/json_parse_utils.h
- include/sasevent.h
Alex,
Please can you review my cpp-common enhancements for nonce-count support?
Thanks,
Matt
> [Reviewer: Alex] cpp-common enhancements for nonce-count support

- include/pdlog.h
- include/syslog_facade.h
- src/pdlog.cpp
Switch to a less congested logging facility for ENT logs
> [Reviewer AMC] Switch ENT logging channel to local7

- include/utils.h
- src/utils.cpp
We copy these three lines of code around a lot, so I've just made them a common function.
> [Reviewer: Alex] Implement get_time in Utils

- include/utils.h
- src/utils.cpp
This commonizes the `daemonize` function from Sprout (and adds the second fork() call to match our python version of this function).
> Reviewer Rob - Common daemonize

- src/alarm.cpp
Matching change to https://github.com/Metaswitch/clearwater-snmp-handlers/pull/137
> [Reviewer: Andrew] Allow running clearwater-snmp-handlers UT without /var/run/clearwater

- include/alarm.h
- test_utils/mockalarm.h
The main function in this PR is the ability to lock the HTTP stack.
I've also added a virtual destructor for MultiStateAlarm, and a MockMultiStateAlarm class.
> Reviewed: Add some MultiStateAlarm infrastructure

- src/snmp_agent.cpp
> Reviewed: Commented out tcpdump line

- include/load_monitor.h
- include/sasevent.h
- src/httpstack.cpp
- src/load_monitor.cpp
- test_utils/mockloadmonitor.hpp
Adds more detail to the load monitor logs and adds SAS logs
Fixes #507, tested live.
> [Reviewer: Rob] Add more detail to load monitor logs

- include/utils.h
- src/utils.cpp
Tested at https://github.com/Metaswitch/cpp-common-test/pull/20/commits/a3056239ff2d44e1ed9fb9e4e5686d73a904b896
> [Reviewer: Ellie] Add uint64_t overload of overflow_less_than

- src/snmp_agent.cpp
> [Reviewer: Ellie] Add comment detailing dangers of snmp_terminate on centos.

- include/sasevent.h
Alex - any chance of a quick review of this 1 line change?
once its reviewed, I'll run the update cpp-common script.  I'm assuming that won't need reviewing, but let me know if that's wrong.  
thanks
> add SAS event space for houdini

- include/alarmdefinition.h
Add a comparison for alarm severities
> [No reviewer] Add alarm comparison operators

- include/localstore.h
- src/localstore.cpp
So that I could write the UT in the other pull request.
> [Reviewer: RKD] Add ability to force error in local store set

- include/httpclient.h
- include/httpconnection.h
- src/httpclient.cpp
- src/httpconnection.cpp
- src/httpconnectionpool.cpp
Ellie,
Please can you review my changes to refactor HttpConnection into HttpClient?  Not sure how best to review this - maybe just look through the headers to see the new structure (the C++ code basically just follows as-is).
I've UT-ed but not live-tested yet.  Sending this to you early as Tom is likely to want to build on it.
Cheers,
Matt
> [Reviewer: Ellie] Refactor most of HttpConnection into HttpClient

- include/utils.h
- src/utils.cpp
Ellie,
As discussed, we'd like a common function in cpp-common to get an IPv6 address in brackets. This does that.
There's a separate pull request coming for the associated tests in cpp-common-test.
> [Reviewer: EM] Add function to bracket IPv6 addresses

- test_utils/fakecurl.hpp
Allow a Response to be created from a body and a HTTP code
> [No reviewer] Add a new Response constructor

- include/baseresolver.h
- include/weightedselector.h
- src/baseresolver.cpp
Rich
Can you review this please? - its the change you suggested as part of the Load-balancing you reviewed.  
Sprout UT's have been run.  is there any other component likely to be affected by this?
Thanks
> [Reviewer: RJW2] BGCF-20 Break out WeightedSelector into a separate class

- include/baseresolver.h
- include/weightedselector.h
As you know BJR2 made some changes yesterday.  A couple of minor amendments have been made to WeightedSelector and a get_weight function has had to be added to baseresolver.  Could you please check these are ok?
> [Reviewer: RJW2]  Minor Additions for WeightedSelector

- include/utils.h
- src/utils.cpp
This moves it out of Homestead so Sprout can use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/cpp-common/564)
> [Reviewer: Ellie] Add function to convert binary to hex

- include/snmp_internal/snmp_table.h
> [No reviewer] Drop info logs to debug level, remove some debug logs

- include/httpclient.h
- include/httpconnection.h
- include/utils.h
- src/httpclient.cpp
- src/httpconnection.cpp
- src/utils.cpp
- test_utils/curl_interposer.cpp
- test_utils/fakecurl.cpp
- test_utils/fakecurl.hpp
A rework of #581, but starting at `master`.
As in that one, there are a handful of trivial UT fixes to be made in sprout and memento, that would need to be coordinated with this.
> Support querying https URLs

- src/httpstack.cpp
> [Reviewer: Alex] Make HTTP socket world-writeable

- src/httpclient.cpp
Hopefully one last wrinkle in this set of curl changes.
I don't expect this to make any difference to external behaviour, but it's cleaner not to attempt to resolve something that's already an IP address.
> Don't resolve something that's already an IP address

- include/alarmdefinition.h
- include/pdlog.h
Adding extra reserved blocks for alarms and logs.
> [Reviewer: SR2] Add extra reserved blocks for alarms and logs

- include/sasevent.h
Update for clearwater-sas-resources pull request 124.
No reviewer as this is a minor datestamp change. Will be merged simultaneously with above pull request.
> Update SAS datestamp

- include/sasevent.h
- src/memcachedstore.cpp
We can get a string from the memcached rc, so use it in the SAS log
**testing**
- live tested
> [Reviewer: Ellie] Better SAS logs for memcached SET errors

- include/sasevent.h
To be merged in and updated with clearwater-sas-resources pull request 127. If the merge date of the aforementioned PR slips beyond 4th Jan then this datestamp will be updated accordingly.
> [INT-72] [Reviewer: CJR] Update SAS resource bundle datestamp

- src/snmp_continuous_increment_table.cpp
- src/snmp_infinite_scalar_table.cpp
- src/snmp_infinite_timer_count_table.cpp
- src/timer_counter.cpp
As at #599 . Just set up the PRs the wrong way round.
> [No reviewer] Thread safer stats

- test_utils/mock_httpclient.h
I've written some UTs in sprout that use this class so I'm confident it works.
> Add a mock HTTP client. 

- src/memcachedstore.cpp
Fix for #609 - increases the memcached timeout as discussed.
> [Reviewer: Seb] Increase timeout

- scripts/stats-c/cw_stat.cpp
Add a timeout to the cw_stat call (as otherwise it blocks forever). Part of the fix for issue https://github.com/Metaswitch/astaire/issues/76
> [Reviewer: Adam] Add a timeout to cw_stat

- include/threadpool.h
Contains a variety of thread pool enhancements:
* A thread pool variant that can take and run any callable object. 
* Allows work items to be added to the pool by move rather than by copy. 
* Adds a `run_once` method to allow the thread pool to be driven in UTs.
> Add a functor thread pool

- include/memcachedstore.h
- src/memcachedstore.cpp
Change to memcached timeouts so that local and remote sites have different timeouts, rather than not having an effective timeout.
> [Reviewer: Seb] Change to have different timeouts for local and remote sites

- src/baseresolver.cpp
- src/diameterresolver.cpp
- src/dnscachedresolver.cpp
This has already been reviewed on another pull request (#624).
> Find min ttl

- include/base64.h
- include/bloom_filter.h
- include/siphash.h
- src/base64.cpp
- src/bloom_filter.cpp
- src/siphash.cpp
Sathiyan, please can you review this bloom filter code? Hopefully self explanatory but let me know if not. siphash.cpp is taken from the reference implementation of SipHash, so it's not worth reviewing that file!
Tested in UT.
> Add a serializable bloom filter implementation

- include/sasevent.h
Update resource bundle identifier, and add new Event Space
> [Reviewer:HJS] Update sas_event.h following SAS changes

- include/utils.h
- src/utils.cpp
This adds some utility functions to help with wildcard parsing
Tested in UTs and live
> [Reviewer: Krista] Add wildcard matching functions

- include/sasevent.h
Update SAS datestamp for resource bundle update.
Master only.
> [Reviewer: HJS] SAS datestamp update 20170322

- include/xml_utils.h
- src/xml_utils.cpp
This pulls out the generic XML functions from Sprout/Homestead - the code hasn't changed.
> [Reviewer: Adam] Commonise the XML functions

- include/sasevent.h
Following https://github.com/Metaswitch/clearwater-sas-resources/pull/139
> [Reviewer=BJR2] Update SAS datestamp

- include/xml_utils.h
To neaten up the logic when handling RTRs, I've added this new constant.
(It allows me to set this as default.)
> Add new barring constant

- include/cpp_common_pd_definitions.h
Rename /etc/clearwater/dns_config to /etc/clearwater/dns.json
> [No reviewer] Update filename

- include/xml_utils.h
Add some constants for the call barring field.
> [Reviewer: KH1] Constants for call barring

- include/localstore.h
- src/localstore.cpp
Ellie, please could you review this PR that's needed as part of the UT for https://github.com/Metaswitch/sprout/pull/1830?
> Allow swapping of store DBs to simulate GR failovers

- include/utils.h
- src/utils.cpp
Seb,
We've got a whole bunch of code duplicated between Sprout and Ralf for no reason. This fixes that by moving the code to cpp-common.
> [Reviewer: Seb] Add parse_multi_site_stores_arg

- include/http_connection_pool.h
- include/httpclient.h
- include/httpconnection.h
- src/http_connection_pool.cpp
- src/httpclient.cpp
Sets the HTTP connection and response timeouts according to whether we are connecting a local or remote site.
> [Reviewer: EM] Make HTTP timeouts configurable

- include/memcached_connection_pool.h
- include/memcachedstore.h
- src/memcachedstore.cpp
Fixing what was regressed by split-storage.
> [Reviewer: EM] Move memcached connection timeout code into connection pool

- include/httpconnection.h
- src/httpconnection.cpp
Added a new method for sending PUT requests
> New HTTP PUT method 

- include/utils.h
- src/utils.cpp
[Reviewer AJH] Fix with markups
> Mark RTRs and PPRs in SAS

- src/diameterresolver.cpp
- src/diameterstack.cpp
- src/namespace_hop.cpp
- src/snmp_agent.cpp
- src/timer_counter.cpp
> [No reviewer] Fix up errors from static analysis

- include/utils.h
- src/httpclient.cpp
- src/memcachedstore.cpp
- src/utils.cpp
This is support code to allow us to perform actions when a thread is about to do blocking IO. This PR also contains a small enhancement to allow a stopwatch to be stopped and restarted. No UTs yet - this PR is to get early feedback on the approach before I go any further.
> Add IO hooks

- include/load_monitor.h
- src/load_monitor.cpp
- test_utils/mockloadmonitor.hpp
Add a configurable maximum rate to the load monitor/token bucket. Tested in UTs only.
> [Reviewer: Krista] Add maximum rate

- include/alarmdefinition.h
- include/pdlog.h
Seb,
Fallout from https://github.com/Metaswitch/astaire/pull/93
> [Reviewer: Seb] Add PD and Alarms ranges for Rogers

- include/memcached_connection_pool.h
- include/memcachedstore.h
- src/memcachedstore.cpp
See https://github.com/Metaswitch/astaire/pull/99
> Fix memcached timeouts

- src/memcached_connection_pool.cpp
- src/memcachedstore.cpp
See https://github.com/Metaswitch/astaire/pull/100
> Remove dupliate configuration of memcached connect timeout

- include/httpstack.h
- include/utils.h
For the fix for https://github.com/Metaswitch/homestead/pull/496, we want to be able to do some things we can't currently:
* access the HTTPRequest's StopWatch from a Task
* add and subtract times to the StopWatch
This PR adds those.
**Note** - I haven't yet checked whether we need to add some more tests in cpp-common-test, so we should do that before this is merged.
> [Reviewer: Richard] Tweaks to StopWatch

- test_utils/mock_sas.cpp
- test_utils/mock_sas.h
See https://github.com/Metaswitch/sprout/pull/2017
> Support checking multiple marker values

- include/exception_handler.h
- include/log.h
- include/logger.h
- src/exception_handler.cpp
- src/log.cpp
- src/logger.cpp
Reverts Metaswitch/cpp-common#721
(#721 was merged by mistake)
> Revert "Make exception handling more robust"

- include/exception_handler.h
- include/log.h
- include/logger.h
- src/exception_handler.cpp
- src/log.cpp
- src/logger.cpp
This was reviewed under https://github.com/Metaswitch/cpp-common/pull/721 (that PR was merged by mistake).
> Make exception handling more robust

- include/snmp_agent.h
Part of the fix to https://github.com/Metaswitch/clearwater-issues/issues/2655, required by https://github.com/Metaswitch/clearwater-snmp-handlers/pull/210.
> [Reviewer: Richard] Allow access to Net-SNMP's lock

- include/localstore.h
- include/memcachedstore.h
- include/store.h
Function prototype updates required to work with GMOCK UTs across various components.
> Update get/set_data prototypes for GMOCK UT compatiblity

- include/httpclient.h
Adds the 422 response code. 
I've tested that this compiles.
I'll merge this straight in.
> [Reviewer: Alex] Add new RC

- include/httpstack_utils.h
> Move TimeHandler from Sprout main to httpstack_util

- include/dnscachedresolver.h
- src/dnscachedresolver.cpp
All UTs pass fine. It's a simple change so I've not run FVs over this too.
> increase the dns timeout to a multiple of dns servers used

- test_utils/mock_snmp_counter_table.hpp
Changes for [#2066](https://github.com/Metaswitch/sprout/pull/2066).
> [Reviewer: AJH] Locality Optimization

- include/diameterstack.h
- include/httpstack_utils.h
- src/diameterstack.cpp
- src/httpstack.cpp
Update to be in line with typo fix in the sas-client. PR [here](https://github.com/Metaswitch/sas-client/pull/82).
> [Reviewer: CJR] Fixed Marker ID typo

- include/dnscachedresolver.h
- src/dnscachedresolver.cpp
Has already been reviewed under #761.
> Standardise ordering of DNS records when static cache is involved

- src/diameterstack.cpp
cpp-common changes to go with https://github.com/Metaswitch/homestead/pull/519
> [Reviewer: Adam] Downgrade per-call logs
